### ISSUE TITLE
Redundant steps

### ISSUE THREAD

**Issue by drom** [drjson/stackedit-wavedrom#3]
Do we really need **Template Output Updates** step?
https://github.com/drjson/stackedit-wavedrom#template-output-updates
It seems redundant to me.

**Comment by drjson** [comment]
It's only if you want to output to HTML using a template (like example.html). If you wanted to publish to a blog or save the HTML later to work outside of stackedit.

The user extension hooks into the markdown renderer and replaces the fencing blocks with script blocks that work with WaveDrom. When the stackedit preview gets updated, it parses the script blocks using the newly exposed methods. When exported to HTML, that doesn't happen, so this just pulls in the scripts and calls ProcessAll.

I'll add a comment that that's only required for exporting via template.

**Comment by drom** [comment]
o! I see. Can the code in section **User Extension Code** perform this `<head>` & `<body>` surgery?

**Comment by drjson** [comment]
I think it may be limited by how stackedit works. When exporting to HTML, it takes the markdown rendered HTML and wraps it in the rest of an HTML page (html, head, body, etc) from a default or user defined template. Since this is where we need to put the `<script src=...>` and `onLoad=wavedrom.ProcessAll()`, we have to put it in that template file. On the live preview (which the user extension controls), we hack these into the already created DOM. Then instead of using the ProcessAll, we use RenderWaveForm called whenever the preview is updated.

**Comment by drom** [comment]
You are right. It will save standard `<head>` and `<body>` content. My idea was to insert some script into the body of the document, similar to what you are doing with `<script src=...>` but this time inserted script will load wavedrom scripts and fire `ProcessAll`. How about that?
